[project]
name = "functional-calling-tools"
version = "3.11"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai==1.83.0",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
